image: registry.gitlab.com/anthony.j.martin/aether-report/build-test:latest

cache:
  paths:
  - /apt-cache
  - /go/src/github.com
  - /go/src/golang.org
  - /go/src/google.golang.org
  - /go/src/gopkg.in

stages:
- test
- build
- deploy

before_script:
- mkdir -p /go/src/gitlab.com/anthony.j.martin /go/src/_/builds
- cp -r $CI_PROJECT_DIR /go/src/gitlab.com/anthony.j.martin/aether-report
- ln -s /go/src/gitlab.com/anthony.j.martin /go/src/_/builds/anthony.j.martin
- export CC=clang-5.0
- make dep

unit_tests:
  tags:
  - docker
  stage: test
  script:
  - make test

#junit_tests:
#  tags:
#  - docker
#  stage: test
#  script:
#  - make test-junit
#  artifacts:
#    reports:
#      junit: report.xml

race_detector:
  tags:
  - docker
  stage: test
  script:
  - make race

memory_sanitizer:
  tags:
  - docker
  stage: test
  script:
  - make msan

code_coverage:
  tags:
  - docker
  stage: test
  script:
  - make coverage

code_coverage_report:
  tags:
  - docker
  stage: test
  script:
  - make coverhtml
  artifacts:
    paths:
    - coverage.html
  only:
  - master

lint_code:
  tags:
  - docker
  stage: test
  script:
  - make lint

build_binary:
  tags:
  - docker
  stage: build
  script:
  - make
  artifacts:
    paths:
    - aether-report

build_rpm:
  tags:
    - docker
  image: registry.gitlab.com/anthony.j.martin/aether-report/rpm-builder:latest
  stage: deploy
  variables:
    APPVER: './tools/version.sh'
  before_script:
  - mkdir -p /go/src/gitlab.com/anthony.j.martin /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/anthony.j.martin/aether-report
  - ln -s /go/src/gitlab.com/anthony.j.martin /go/src/_/builds/anthony.j.martin
  script:
  - echo $(./tools/version.sh)-$CI_PIPELINE_ID
  - go-bin-rpm generate -a amd64 -o aether-report-$(./tools/version.sh)-$CI_PIPELINE_ID.rpm --version $(./tools/version.sh)-$CI_PIPELINE_ID
  - curl -fL https://getcli.jfrog.io | sh
  - ./jfrog bt u --user $BINTRAY_USER --key $BINTRAY_KEY --licenses GPL-3.0 --publish "aether-report*.rpm" $BINTRAY_URL/$(./tools/version.sh)-$CI_PIPELINE_ID
  artifacts:
    paths:
    - aether-report*.rpm
