image: registry.gitlab.com/anthony.j.martin/aether-report/build-test:latest

cache:
  paths:
  - /apt-cache
  - /go/src/github.com
  - /go/src/golang.org
  - /go/src/google.golang.org
  - /go/src/gopkg.in

stages:
- test
- build

before_script:
- mkdir -p /go/src/gitlab.com/anthony.j.martin142 /go/src/_/builds
- cp -r $CI_PROJECT_DIR /go/src/gitlab.com/anthony.j.martin142/aether-report
- ln -s /go/src/gitlab.com/anthony.j.martin142 /go/src/_/builds/anthony.j.martin142
- export CC=clang-5.0
- make dep

unit_tests:
  tags:
  - docker
  stage: test
  script:
  - make test

race_detector:
  tags:
  - docker
  stage: test
  script:
  - make race

memory_sanitizer:
  tags:
  - docker
  stage: test
  script:
  - make msan

code_coverage:
  tags:
  - docker
  stage: test
  script:
  - make coverage

code_coverage_report:
  tags:
  - docker
  stage: test
  script:
  - make coverhtml
  only:
  - master

lint_code:
  tags:
  - docker
  stage: test
  script:
  - make lint

build:
  tags:
  - docker
  stage: build
  script:
  - make
  artifacts:
    paths:
    - aether-report
