FROM centos:7
RUN yum install -y rpm-build make; \
    curl -L https://raw.githubusercontent.com/mh-cbon/latest/master/install.sh | GH=mh-cbon/go-bin-rpm sh -xe; \
    curl -L https://raw.githubusercontent.com/mh-cbon/latest/master/install.sh | GH=mh-cbon/changelog sh -xe
WORKDIR /go/src/gitlab.com/anthony.j.martin/aether-report
ENV GOOS=linux
